//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;

[assembly: AssemblyTitle("Xml2DbMapper")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("Release")]
[assembly: AssemblyProduct("Xml2DbMapper")]
[assembly: AssemblyCulture("")]

[assembly: AssemblyCompany("Esaote")]
[assembly: AssemblyCopyright("Copyright ©2020 by Esaote")]
[assembly: AssemblyTrademark("")]

// Generated by the MSBuild WriteCodeFragment class.

